apiVersion: 1

datasources:
  - name: Elasticsearch-SOC
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logs-*,defender-*,tenable-*]"
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: ${ELASTIC_PASSWORD}
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      interval: Daily
      logMessageField: message
      logLevelField: event.severity
    editable: true
    isDefault: true
